---
title: "index"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r, include=FALSE}

#subtitle: <h1>Amplify</h1>

knitr::opts_chunk$set(echo = FALSE, warning = FALSE,  message=FALSE,  fig.height=4,
                      fig.align = "center")
# library(flexdashboard)
# library(shiny)

# "default", "cerulean", "journal", "flatly", "darkly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", "yeti"

# library(bigrquery) # R Interface to Google BigQuery API  
# library(dplyr) # Grammar for data manipulation  
# library(DBI) # Interface definition to connect to databases 
# library(ggplot2) # Data Viz package
# 
# library(dbplyr)
# 
library(tidyverse)
# library(DT)
# 
# library(formattable)
# 
# library(lubridate)
# library(crosstalk)
# 
# library(ggwordcloud)

options(scipen = 999)
theme_set(theme_light())
```



```{r}
#tidyverse::loa

#df<-datasets::s

df<-datasets::airquality


df %>% ggplot(aes(Ozone, Temp))+ geom_point()


```

